name: restaurant_app
description: A new Flutter project.

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.2.0
  flutter_rating_bar: ^4.0.0
  provider: ^6.0.2
  sqflite: ^2.0.2
  path: ^1.8.0
  cached_network_image: ^3.2.0
  android_alarm_manager_plus: ^2.0.5
  rxdart: ^0.27.3
  flutter_local_notifications: ^9.3.2
  intl: ^0.17.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/file/
    - assets/img/
